// Copyright (C) SomaSim LLC. 
// Open source software. Please see LICENSE file for details.

using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace SomaSim.Util
{
    /// <summary>
    /// List pool in a disposable wrapper, so that it can be called as follows:
    /// <pre>
    ///   using (var list = ListPool[int].Allocate()) {
    ///      // ... use the list ...
    ///   }
    /// </pre>
    /// </summary>
    public class ListPool<T>
    {
        // static instance and initialization

        public static readonly int MAX_SIZE = 500;
        public static ListPool<T> Instance { get; private set; }
        static ListPool () { Reset(); }

        public static PooledList Allocate () => Instance._pool.Allocate();

        public static void Free (PooledList element) => Instance._pool.Free(element);

        public static void Reset () {
            Instance?.Release();
            Instance = new ListPool<T>();
            Instance.Initialize();
        }

        // actual functionality

        private ObjectPoolResettable<PooledList> _pool;

        public void Initialize () {
            _pool = new ObjectPoolResettable<PooledList>();
            _pool.Initialize(
                () => new PooledList(this),    // factory
                list => {                   // list initialize
                    Logger.AssertInEditor(list.Count == 0, "Non-empty pooled list? Someone held on to it for too long!");
                    if (list.Count > 0) { list.Clear(); }
                },
                list => {                   // list reset
                    bool oversized = list.Count > MAX_SIZE;
                    list.Clear();
                    if (oversized) { list.TrimExcess(); }
                },
                list => {                   // list destroy
                    Logger.AssertInEditor(list.Count == 0, "Destroying a non-empty pooled list? Someone held on to it for too long!");
                }
            );
        }

        public void Release () => _pool.Release();

        // lists generated by this pool

        [DebuggerDisplay("{DebugString}")]
        [DebuggerTypeProxy(typeof(ListPool<>.PooledListDebugView))]
        public class PooledList : List<T>, IDisposable
        {
            private static int _gensym = 1;

            private int _id;
            private ListPool<T> _parent;

            internal PooledList (ListPool<T> parent) {
                _parent = parent;
                _id = _gensym++;
            }

            public void Dispose () => _parent._pool.Free(this);

            private string DebugString => $"PooledList #{_id}: {Count} elements of type {typeof(T).Name}";
        }

        // debug view

        private class PooledListDebugView
        {
            private List<T> _source;

            public PooledListDebugView (List<T> source) => _source = source;

            [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
            public T[] Entries => _source.ToArray();
        }
    }
}
